database:
  user: "user"
  user: "user"
  name: "db"
  host: "postgres"
  port: "5432"
  password: "pass"
chain:
  name: BLOCX
  id: 86996
  clConfigPath: node
  elConfigPath: "/explorer-configs/network-params.json"
  configPath: "/explorer-configs/config.yaml"
  genesisTimestamp: 1741416415
  clConfig:
    configName: "BLOCX"
    slotsPerEpoch: 32
    secondsPerSlot: 3
    depositChainID: 86996
frontend:
  enabled: true # Enable or disable to web frontend
  debug: true
  # imprint: "./imprint.html"  
  siteDomain: "http://localhost:8080"
  siteName: "BLOCX. Validator Explorer" 
  siteSubtitle: "BLOCX. Validator explorer" 
  csrfAuthKey: '0123456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0123456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  sessionSecret: "11111111111111111111111111111111"
  # elCurrency: "ETH"
  # clCurrency: "ETH"
  # clCurrencyDivisor: 64
  # elCurrencyDivisor: 64
  mainCurrency: "ETH"
  slotViz:
    enabled: true
    hardforkEpoch: 0
  server:
    host: "0.0.0.0" 
    port: "8080" 
  database:
    user: "user"
    name: "db"
    host: "postgres"
    port: "5432"
    password: "pass"
  readerDatabase:
    user: "user"
    name: "db"
    host: "postgres"
    port: "5432"
    password: "pass"
  writerDatabase:
    user: "user"
    name: "db"
    host: "postgres"
    port: "5432"
    password: "pass"

readerDatabase:
  user: "user"
  name: "db"
  host: "postgres"
  port: "5432"
  password: "pass"
writerDatabase:
  user: "user"
  name: "db"
  host: "postgres"
  port: "5432"
  password: "pass"
bigtable:
  project: explorer
  instance: explorer
  emulator: true
  emulatorHost: lbt
  emulatorPort: 9000
indexer:
  enabled: true 
  indexMissingEpochsOnStartup: true 
  node:
    host: "209.145.57.126" 
    port: "5052" 
    type: "lighthouse" 
    pageSize: 100 
  eth1Endpoint: 'http://209.145.57.126:8545'
  eth1DepositContractFirstBlock: 0
eth1ErigonEndpoint: http://209.145.57.126:8545
eth1GethEndpoint: http://209.145.57.126:8545
redisCacheEndpoint: 'redis:6379'
redisSessionStoreEndpoint: 'redis:6379'
tieredCacheProvider: 'redis'
monitoring:
  enabled: true
  serviceMonitoringConfigurations:
    - name: "eth1indexer"
      duration: 1s
    - name: "latestProposedSlotUpdater"
      duration: 1s
    - name: "epochUpdater"
      duration: 1s
    - name: "rewardsExporter"
      duration: 1s
    - name: "mempoolUpdater"
      duration: 1s
    - name: "indexPageDataUpdater"
      duration: 1s
    - name: "latestBlockUpdater"
      duration: 1s
    - name: "headBlockRootHashUpdater"
      duration: 1s
    - name: "relaysUpdater"
      duration: 1s
    - name: "ethstoreExporter"
      duration: 1s
    - name: "statsUpdater"
      duration: 1s
    - name: "slotExporter"
      duration: 1s
    - name: "statistics"
      duration: 1s
    - name: "lastExportedStatisticDay"
      duration: 1s
    - name: "slotVizUpdater"
      duration: 1s
    - name: "slotUpdater"
      duration: 1s
    - name: "ethStoreStatistics"
      duration: 1s


# ratelimitUpdater:
#   enabled: true
#   updateInterval: 5s
