# Database credentials
database:
  user: "user"
  name: "db"
  host: "172.29.0.2"
  port: "5432"
  password: "pass"
# Chain network configuration
chain:
  name: akelu
  id: 9513
  clConfigPath: node
  elConfigPath: "./local-deployment/network-params.json"
  configPath: "./config/mainnet.chain.yml"
  genesisTimestamp: 1742818532
  clConfig:
    configName: "akelu"
    slotsPerEpoch: 32
    secondsPerSlot: 3
    depositChainID: 9513
# Note: It is possible to run either the frontend or the indexer or both at the same time
# Frontend config
frontend:
  enabled: true # Enable or disable to web frontend
  debug: true
  imprint: "./imprint.html"  # Path to the imprint page content
  siteDomain: "http://localhost:8080"
  siteName: "Kintsugi Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Kintsugi explorer" # Subtitle shown on the main page
  csrfAuthKey: '0123456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0123456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  sessionSecret: "11111111111111111111111111111111"
  # elCurrency: "ETH"
  # clCurrency: "ETH"
  # clCurrencyDivisor: 18
  # elCurrencyDivisor: 18
  mainCurrency: "ETH"
  slotViz:
    enabled: true
    hardforkEpoch: 0
  server:
    host: "0.0.0.0" # Address to listen on
    port: "8080" # Port to listen on
  database:
    user: "user"
    name: "db"
    host: "172.29.0.2"
    port: "5432"
    password: "pass"
  readerDatabase:
    user: "user"
    name: "db"
    host: "172.29.0.2"
    port: "5432"
    password: "pass"
  writerDatabase:
    user: "user"
    name: "db"
    host: "172.29.0.2"
    port: "5432"
    password: "pass"

readerDatabase:
  user: "user"
  name: "db"
  host: "172.29.0.2"
  port: "5432"
  password: "pass"
writerDatabase:
  user: "user"
  name: "db"
  host: "172.29.0.2"
  port: "5432"
  password: "pass"
bigtable:
  project: explorer
  instance: explorer
  emulator: true
  emulatorHost: 172.29.0.3
  emulatorPort: 9000
  # flashSecret: "" # Encryption secret for flash cookies
# Indexer config
indexer:
  enabled: true # Enable or disable the indexing service
  # fullIndexOnStartup: true # Perform a one time full db index on startup
  # indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
  node:
    host: "172.19.0.3" # Address of the backend node
    port: "5052" # GRPC port of the Prysm node
    type: "lighthouse" # can be either prysm or lighthouse
    pageSize: 100 # the amount of entries to fetch per paged rpc call, TODO set to 500
  eth1Endpoint: 'http://172.19.0.2:8545'
  eth1DepositContractFirstBlock: 0
eth1ErigonEndpoint: http://172.19.0.2:8545
eth1GethEndpoint: http://172.19.0.2:8545
redisCacheEndpoint: '172.29.0.4:6379'
redisSessionStoreEndpoint: '172.29.0.4:6379'
tieredCacheProvider: 'redis'
  # Note: 0 is correct, but due to an underflow bug (being fixed), doesn't work.

monitoring:
  enabled: true
  serviceMonitoringConfigurations:
    - name: "eth1indexer"
      duration: 1s
    - name: "latestProposedSlotUpdater"
      duration: 1s
    - name: "epochUpdater"
      duration: 1s
    - name: "rewardsExporter"
      duration: 1s
    - name: "mempoolUpdater"
      duration: 1s
    - name: "indexPageDataUpdater"
      duration: 1s
    - name: "latestBlockUpdater"
      duration: 1s
    - name: "headBlockRootHashUpdater"
      duration: 1s
    - name: "relaysUpdater"
      duration: 1s
    - name: "ethstoreExporter"
      duration: 1s
    - name: "statsUpdater"
      duration: 1s
    - name: "slotExporter"
      duration: 1s
    - name: "statistics"
      duration: 1s
    - name: "lastExportedStatisticDay"
      duration: 1s
    - name: "slotVizUpdater"
      duration: 1s
    - name: "slotUpdater"
      duration: 1s
    - name: "ethStoreStatistics"
      duration: 1s


ratelimitUpdater:
  enabled: true
  updateInterval: 5s